wireplumber.profiles = {
  main = {
    monitor.libcamera = disabled
  }
}

monitor.v4l2.rules = [
  {
    matches = [
      {
        api.v4l2.cap.driver = "isys"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
  {
    matches = [
      {
        node.name = "v4l2_input._sys_devices_virtual_video4linux_video48"
      }
    ]
    actions = {
      update-props = {
        media.role = "Camera"
        node.description = "Built-in Webcam"
        priority.session = 1000
      }
    }
  }
]
