softdep intel_cvs pre: intel_skl_int3472_discrete ivsc
softdep intel_ipu6 pre: intel_cvs
softdep intel_ipu6_isys pre: intel_ipu6
softdep ov02c10 pre: intel_ipu6_isys
softdep v4l2loopback pre: ov02c10

